SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP TABLE IF EXISTS `tests` ;

CREATE TABLE IF NOT EXISTS `tests` (
  `test_id` INT NOT NULL AUTO_INCREMENT,
  `test_date` DATETIME NULL,
  `test_end_time` DATETIME NULL,
  PRIMARY KEY (`test_id`),
  INDEX `END_TIME_INDEX` (`test_end_time` ASC) )
ENGINE = InnoDB;

DROP TABLE IF EXISTS `questions` ;

CREATE TABLE IF NOT EXISTS `questions` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `test_id` INT NULL,
  `question` VARCHAR(255) NULL,
  `response_type` VARCHAR(10) NULL,
  PRIMARY KEY (`question_id`),
  INDEX `TEST_INDEX` (`test_id` ASC),
  CONSTRAINT `FK_TEST_QUESTION`
    FOREIGN KEY (`test_id`)
    REFERENCES `tests` (`test_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `response` ;

CREATE TABLE IF NOT EXISTS `response` (
  `response_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NULL,
  `test_id` INT NULL,
  PRIMARY KEY (`response_id`),
  INDEX `FK_RESPONSE_TEST_idx` (`test_id` ASC),
  INDEX `INDEX_USER_ID` (`user_id` ASC),
  CONSTRAINT `FK_RESPONSE_TEST`
    FOREIGN KEY (`test_id`)
    REFERENCES `tests` (`test_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `answers` ;

CREATE TABLE IF NOT EXISTS `answers` (
  `response_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer` LONGTEXT NULL,
  PRIMARY KEY (`response_id`, `question_id`),
  INDEX `FK_ANSWER_QUESTION_idx` (`question_id` ASC),
  CONSTRAINT `FK_ANSWER_RESPONSE`
    FOREIGN KEY (`response_id`)
    REFERENCES `response` (`response_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ANSWER_QUESTION`
    FOREIGN KEY (`question_id`)
    REFERENCES `questions` (`question_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
